quarkus.application.name=registry-reactive-example
quarkus.http.port=8484
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app_user
%dev.quarkus.datasource.reactive.url=postgresql://db:5432/appdb
%dev.quarkus.datasource.reactive.postgresql.ssl-mode=verify-full
%dev.quarkus.datasource.reactive.hostname-verification-algorithm=HTTPS
%dev.quarkus.datasource.reactive.trust-certificate-pem=true
%dev.quarkus.datasource.reactive.trust-certificate-pem.certs=/certs/ca.crt
%dev.quarkus.datasource.reactive.key-certificate-pem=true
%dev.quarkus.datasource.reactive.key-certificate-pem.certs=/certs/client.crt
%dev.quarkus.datasource.reactive.key-certificate-pem.keys=/certs/client.key