quarkus.application.name=registry-reactive-example
quarkus.http.port=8484
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app_user
quarkus.datasource.reactive.url=postgresql://localhost:5432/appdb